name: "Lighthouse Badger"

on:
  workflow_dispatch:

jobs:
  lighthouse-badger-easy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "Lighthouse Badger disabled for personal portfolio deployment."
