name: Prettier code formatter

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "Prettier check disabled for personal portfolio deployment."
