name: Integration tests

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  disable-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "Integration tests disabled for personal portfolio deployment."
